### ISSUE TITLE
Cursor on back to members isn't pointer on the default theme

### ISSUE THREAD

**Issue by Azevedo-Erick** [revoltchat/revite#286]
Well, the cursor isn't transforming in pointer on "Back to members" button (on the search tab) on the default theme. The solution can be:

```css
.jqHpRY{
     cursor: pointer;
    display: inline-block;
}
```
